finetune_weights: /mnt/projects/ObjectDetection/weights/yolo_weights/wework_coco_v5x6/weights/best.pt

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: 'wework_coco_v5x6'

cfg: ''
data: people_detection/wework_coco_v2.yaml
hyp: data/hyp.finetune.yaml
epochs: 50
batch_size: 16
img_size: [1280, 1280]
device: '0'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4