finetune_weights: /mnt/ActionRecog/weights/yolo_weights/ORIG/yolov5x6.pt

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: 'UAV_VisDrone_bdd100k_v5x6'

cfg: ''
data: vehical_count/UAV_VisDrone_bdd100k.yaml
hyp: data/hyp.finetune.yaml
epochs: 50
batch_size: 64
img_size: [1280, 1280]
device: '0'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4