finetune_weights: /mnt/ActionRecog/weights/yolo_weights/ORIG/yolov5x6.pt

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: Motor_v5x6

cfg: ''
data: motor/Motor.yaml
hyp: data/hyp.finetune.yaml
epochs: 50
batch_size: 16
img_size: [1280, 1280]
device: '0,1,2,3'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4