finetune_weights: /mnt/ActionRecog/weights/yolo_weights/ORIG/yolov5x6.pt

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: 'people_vehical_v5x6'

cfg: ''
data: people_vehical/people_vehical.yaml
#data: people_detection/wework_coco.yaml
hyp: people_vehical/hyp.finetune_v2.yaml
epochs: 100
batch_size: 16
img_size: [1280, 1280]
device: '0'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4