finetune_weights: ''

project: /mnt/projects/ObjectDetection/weights/yolo_weights
name: 'people_vehical_v5x_conv'

cfg: models/yolov5x_conv.yaml
data: people_vehical/people_vehical.yaml
#data: people_detection/wework_coco.yaml
hyp: people_vehical/hyp.finetune_v2.yaml
epochs: 100
batch_size: 16
img_size: [1280, 704]
device: '0'
test_task: val
workers: 16

conf_thresh: 0.2
iou_thresh: 0.4